version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersmicro
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

volumes:
  postgres-data:
    driver: local
    external: false